// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.mi.car.jsse.easysec.micar.jsse;

public final class CertVerifyProto {
  private CertVerifyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
