// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.mi.car.jsse.easysec.micar.jsse;

public interface generateSignatureParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jsse.generateSignatureParam)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bytes signature = 1;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();
}
