// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.mi.car.jsse.easysec.micar.jsse;

public interface IdentityCertParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jsse.IdentityCertParam)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string cert = 1;</code>
   * @return The cert.
   */
  String getCert();
  /**
   * <code>string cert = 1;</code>
   * @return The bytes for cert.
   */
  com.google.protobuf.ByteString
      getCertBytes();
}
