// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.mi.car.jsse.easysec.micar.jsse;

/**
 * Protobuf type {@code jsse.IdentityCertParam}
 */
public  final class IdentityCertParam extends
    com.google.protobuf.GeneratedMessageLite<
        IdentityCertParam, IdentityCertParam.Builder> implements
    // @@protoc_insertion_point(message_implements:jsse.IdentityCertParam)
    IdentityCertParamOrBuilder {
  private IdentityCertParam() {
    cert_ = "";
  }
  public static final int CERT_FIELD_NUMBER = 1;
  private String cert_;
  /**
   * <code>string cert = 1;</code>
   * @return The cert.
   */
  @Override
  public String getCert() {
    return cert_;
  }
  /**
   * <code>string cert = 1;</code>
   * @return The bytes for cert.
   */
  @Override
  public com.google.protobuf.ByteString
      getCertBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(cert_);
  }
  /**
   * <code>string cert = 1;</code>
   * @param value The cert to set.
   */
  private void setCert(
      String value) {
    Class<?> valueClass = value.getClass();
  
    cert_ = value;
  }
  /**
   * <code>string cert = 1;</code>
   */
  private void clearCert() {
    
    cert_ = getDefaultInstance().getCert();
  }
  /**
   * <code>string cert = 1;</code>
   * @param value The bytes for cert to set.
   */
  private void setCertBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    cert_ = value.toStringUtf8();
    
  }

  public static IdentityCertParam parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static IdentityCertParam parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static IdentityCertParam parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static IdentityCertParam parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static IdentityCertParam parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static IdentityCertParam parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static IdentityCertParam parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static IdentityCertParam parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static IdentityCertParam parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static IdentityCertParam parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static IdentityCertParam parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static IdentityCertParam parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(IdentityCertParam prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code jsse.IdentityCertParam}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        IdentityCertParam, Builder> implements
      // @@protoc_insertion_point(builder_implements:jsse.IdentityCertParam)
      IdentityCertParamOrBuilder {
    // Construct using com.mi.car.jsse.easysec.micar.jsse.IdentityCertParam.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string cert = 1;</code>
     * @return The cert.
     */
    @Override
    public String getCert() {
      return instance.getCert();
    }
    /**
     * <code>string cert = 1;</code>
     * @return The bytes for cert.
     */
    @Override
    public com.google.protobuf.ByteString
        getCertBytes() {
      return instance.getCertBytes();
    }
    /**
     * <code>string cert = 1;</code>
     * @param value The cert to set.
     * @return This builder for chaining.
     */
    public Builder setCert(
        String value) {
      copyOnWrite();
      instance.setCert(value);
      return this;
    }
    /**
     * <code>string cert = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCert() {
      copyOnWrite();
      instance.clearCert();
      return this;
    }
    /**
     * <code>string cert = 1;</code>
     * @param value The bytes for cert to set.
     * @return This builder for chaining.
     */
    public Builder setCertBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCertBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:jsse.IdentityCertParam)
  }
  @Override
  @SuppressWarnings({"unchecked", "fallthrough"})
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new IdentityCertParam();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          Object[] objects = new Object[] {
            "cert_",
          };
          String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<IdentityCertParam> parser = PARSER;
        if (parser == null) {
          synchronized (IdentityCertParam.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<IdentityCertParam>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:jsse.IdentityCertParam)
  private static final IdentityCertParam DEFAULT_INSTANCE;
  static {
    IdentityCertParam defaultInstance = new IdentityCertParam();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      IdentityCertParam.class, defaultInstance);
  }

  public static IdentityCertParam getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<IdentityCertParam> PARSER;

  public static com.google.protobuf.Parser<IdentityCertParam> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

