// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.mi.car.jsse.easysec.micar.jsse;

public interface X509CertChainParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jsse.X509CertChainParam)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string chain = 1;</code>
   * @return The chain.
   */
  String getChain();
  /**
   * <code>string chain = 1;</code>
   * @return The bytes for chain.
   */
  com.google.protobuf.ByteString
      getChainBytes();
}
